language: node_js
node_js: 7
cache:
  directories:
  - node_modules
  - bower_components
  - "${NVM_PATH}_modules"
env:
- CXX=g++-4.8
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - g++-4.8
install:
- npm install
script: echo "Deploying!"
before_deploy: npm run build
deploy:
- provider: firebase
  skip_cleanup: true
  on:
    branch: master
  project: devfest-gh
  token:
    secure: "dte4r41o934RY1mU5PHH3k5/8W73CTr/cGX0c9qmGWeQJ69FYDRxCv/SE4ICpOGJ8ECmM43FGeB6jc0wsjtBfi8Jb4jIdS7E2DUWSP0HKq0WFoaVUzC45BBCSnmry+AfnuU2SylTbjijGpP1qDL87hStN6nLE/FdtggBubca+/WOB40q8zaRJcNlqofqF/tCrsFqhcCQTOdZWqZA9603ldWAtNZYnj6VNGSLQJPqsLpcWfeS4SingAq7JpidLUez7gmaDinCWYLHxWfR/uvroPwzRQX+ssKZ+ONGKYONvIHun6HR8B/TfaDgs1TysUqNgcokVIJ/Kk3q9XDW6Q0GnydRlVaQTQOalmAm8jjiF59q+158L++u4IvfjnZk1iZ4Xf94srrGQ4liHzqNTQRu4971vf2u2424WpNK84piVDblrXIRRd7oRRdgTDa1nw9rN2uh+Qj54DXzFhZ4FfxatQjfIPVNJsHnznHNL41wo+klbqQxF8vmj11hDKGPtqwcNs6pxBcNRzU+23CKEDFQAOyswHTgzaEOSO+71Ebkp8iz+j7KOBQmLPt4BIYB2FFmkD2HspjDFwpwQk+PBUerZqKxIzQQBgSWZQg1vG76e9tuvb0S1s4bzPfpuEruy6tv1ac1H2AOtSBabe3E0DuzYzyZIEBOHWE6Oil7fgkKn2M="
